version: '3.5'

volumes:
  database:
    name: ticketdb
    driver: local
    driver_opts:
      device: /database
      o: bind
      type: none

networks:
  ticketnet:
    name: ticketnet

services:
  main:
    container_name: ticket_it
    build: ./requirement/main
    stop_signal: SIGINT
